spring.application.name=graph.app

server.port=${PORT:8080}

cognodb.uri=${COGNODB_URI}
cognodb.username=${COGNODB_USERNAME}
cognodb.password=${COGNODB_PASSWORD}

frontend.origin=${FRONTEND_ORIGIN:http://localhost:5173}